name: Automerge phnx47[bot] sync

on:
  pull_request:
    types: [labeled]
    branches:
      - "main"

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-22.04
    if: github.event.label.name == 'sync' && github.actor == 'phnx47-bot'
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GH_FULL_PAT }}
